import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageType = 'en' | 'ar' | 'de' | 'fr' | 'es' | 'tr';

interface LanguageContextType {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations: Record<LanguageType, Record<string, string>> = {
  en: {
    // Nav
    navHome: "Home",
    navMyLogs: "My Logs",
    navReports: "Reports",
    navLogExport: "Log Export",
    navActive: "Active Now",
    navNotices: "Notices",
    navStaff: "Staff Management",
    navSchedules: "Schedules",
    navWorksite: "Worksite Settings",
    navSettings: "Settings",
    navSignOut: "Sign Out",
    navLogin: "Login",
    navRegister: "Sign Up",

    // General
    save: "Save Changes",
    cancel: "Cancel",
    admin: "Admin",
    employee: "Employee",
    loading: "Loading...",
    status: "Status",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    all: "All",
    warning: "Warning",

    // Login / Sign Up
    loginTitle: "Access Your Workspace",
    signUpTitle: "Register Your Workspace",
    tagline: "Empowering secure, real-time workplace attendance logging with automated geofencing.",
    emailLabel: "Work Email Address",
    passwordLabel: "Password",
    signInBtn: "Sign Into Account",
    noAccountText: "Need a new company workspace?",
    signUpBtn: "Register Company & Admin",
    fullNameLabel: "Full Legal Name",
    companyIdLabel: "Company ID (A-Z, 0-9)",
    companyNameLabel: "Company Display Name",
    alreadyHaveAccount: "Already have an account?",
    signingIn: "Signing in...",
    creatingWorkspace: "Creating workspace...",

    // Dashboard
    goodMorning: "Good Morning",
    welcomeBack: "Welcome back",
    activeShift: "Active Shift",
    noShiftToday: "No scheduled shift for today",
    geofenceStatus: "Geofence Status",
    insideGeofence: "Inside Geofence Range",
    outsideGeofence: "Outside Geofence Range",
    locationChecking: "Verifying your live coordinates...",
    locationDisabled: "Location permission is required to clock in.",
    noActiveLogsToday: "You haven't logged any attendance today.",
    clockedInSuccess: "Clocked in successfully!",
    clockedOutSuccess: "Clocked out successfully!",
    selectProject: "Select Project...",
    clockInBtn: "Clock In (Attend)",
    clockOutBtn: "Clock Out (Depart)",
    activeLogHeader: "Today's Log",
    hoursWorked: "Hours Worked",
    ongoing: "Ongoing",
    exemptionStatus: "Exemption Status",
    nightShiftExemption: "Night Shift Exemption Active",
    noExemption: "Standard Rules (10 AM Auto-close)",
    todaysShift: "Scheduled Hours:",
    selectProjectError: "Please select a project before clocking in.",

    // My Logs / History
    myLogsHeader: "Attendance History",
    myLogsSub: "Verify and view all your recorded clock-in and clock-out logs",
    exportPdf: "Export PDF Report",
    dateCol: "Date",
    projectCol: "Project",
    checkInCol: "Check In",
    checkOutCol: "Check Out",
    durationCol: "Duration",
    hrs: "hrs",
    mins: "mins",
    totalHours: "Total Hours",
    noLogsFound: "No attendance logs found for this period.",
    filterByMonth: "Filter by Month",

    // Settings
    settingsHeader: "Account Settings",
    settingsSub: "Manage your personal credentials, workspace preferences, and profile properties",
    personalInfoTitle: "Personal Information",
    personalInfoSub: "Verify and update your basic profile parameters",
    deptLabel: "Assigned Department (Readonly)",
    employeeIdLabel: "Employee/Staff ID",
    saveProfileBtn: "Save Profile Information",
    savingProfile: "Saving profile...",
    companyProfileTitle: "Company Profile (Admin Only)",
    companyProfileSub: "Modify company profile, display name, and system registration ID",
    companyDisplayName: "Company Display Name",
    companyRegId: "Company Registration ID",
    companyWarning: "Changing the Company ID will securely migrate all active employees, shifts, logs, and projects to the new ID.",
    savingCompany: "Updating Company...",
    saveCompanyBtn: "Save Company Settings",
    passResetTitle: "Password Reset",
    passResetSub: "Modify your authentication credentials safely",
    newPassLabel: "New Password",
    confirmPassLabel: "Confirm New Password",
    savingPass: "Updating Password...",
    savePassBtn: "Update Password",
    activeCompany: "Active Company",
    companyIdFieldLabel: "Company ID:",
    profilePhotoLabel: "Profile Photo",
    selectPresetAvatar: "Select Preset Avatar",
    customPhotoUrl: "Custom Photo URL",
    saudiWpsMudadBankingDetails: "Saudi WPS / Mudad Banking Details",
    iqamaLabel: "National ID / Iqama (10 digits)",
    bankCodeLabel: "Bank Code",
    ibanLabel: "IBAN Number (24 chars starting with SA)",
    selectBank: "— Select Bank —",

    // Admin Reports
    reportsTitle: "Organizational Reports",
    reportsSub: "Aggregate attendance intelligence, payroll cycles, and work hours analytics",
    periodLabel: "Custom Date Filter Period",
    allDepartments: "All Departments",
    allProjects: "All Projects",
    employeeNameCol: "Employee Name",
    workedDaysCol: "Worked Days",
    totalHrsCol: "Total Hours",
    overtimeCol: "Overtime Hours",
    adjustmentsCol: "Payroll Adjustments",
    deductionsLabel: "Other Deductions (SAR)",
    reimbursementsLabel: "Reimbursements (SAR)",
    absentDaysLabel: "Absent Days",
    saveAdjustments: "Save Payroll Adjustments",
    monthlyCyclesNote: "Note: Payroll cycles run monthly from the 26th of the previous month to the 25th of the current month.",

    // Log Export
    exportTitle: "Attendance Log Export",
    exportSub: "Download comprehensive system logs in standard Excel or PDF format",
    exportCsvBtn: "Export Excel (CSV)",
    exportPdfBtn: "Export PDF Archive",
    exportPreviewTitle: "Log Preview",

    // Active Now
    activeTitle: "Currently Clocked In",
    activeSub: "Real-time view of staff members currently on duty",
    noActiveStaff: "No staff members are currently clocked in.",

    // Notices / Broadcasts
    noticesTitle: "Company Notices & Announcements",
    noticesSub: "Post target broadcasts to specific projects or employees",
    addNotice: "Create New Announcement",
    noticeSubject: "Subject / Title",
    noticeContent: "Message / Content",
    targetProjects: "Target Projects (Empty for all)",
    targetUsers: "Target Staff (Empty for all)",
    publishBtn: "Publish Announcement",
    activeBroadcasts: "Active Announcements",

    // Staff Management
    staffTitle: "Staff Directory & Roles",
    staffSub: "Register, modify, and adjust employee parameters and salaries",
    addStaffBtn: "Register New Employee",
    editStaffTitle: "Edit Employee Profile",
    roleLabel: "Workspace Role",
    salaryLabel: "Base Salary (SAR)",
    stdHoursLabel: "Standard Monthly Hours",
    saveStaffBtn: "Save Employee Details",

    // Schedules
    scheduleTitle: "Shift Schedules & Exemptions",
    scheduleSub: "Assign designated shift hours and night exemptions",
    addScheduleBtn: "Create New Shift",
    daysLabel: "Applicable Work Days",
    startEndLabel: "Start & End Time",
    disableAutoCloseLabel: "Enable Night Shift (Disable 10 AM Auto-close)",

    // Worksite Settings
    worksiteTitle: "Geofence & Worksite Geolocation",
    worksiteSub: "Configure GPS coordinates and acceptable radius for checking in",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    radiusLabel: "Acceptable Radius (Meters)",
    saveWorksiteBtn: "Save Worksite Coordinates",
    getCurrentLocationBtn: "Fetch Current GPS Coordinates",

    // Dashboard Extras
    dbSub: "Attendance tracked via geofencing site boundaries",
    dbSelectMonitoringSite: "Monitoring Site: Select...",
    distanceLabel: "Distance",
    dbNoWorksiteSelected: "No worksite selected for check-in.",
    shiftInactive: "Shift Inactive",
    dbChooseSite: "Choose a site to begin",
    policyTitle: "Attendance Policy",
    policyRule1: "Clock-in requires physical presence on site.",
    policyRule2: "Clock-out anywhere; flagged if outside zone.",
    policyRule3: "Unclosed shifts auto-terminate at 23:59 unless exempt.",
    geofenceError: "Geofence Restriction: You must be at the worksite to Clock In.",
    selectWorksiteError: "Please select a worksite first.",
    shiftActionFailed: "Shift action failed: ",
    shiftActive: "Shift Active",
    hello: "Hello",
    insideSiteZone: "You are inside the site zone",
    outsideSiteZone: "Warning: Outside site boundary",
    geofenceDisabled: "GPS verification is inactive or disabled.",
    clockedInTime: "Clocked in @",

    // History Extras
    fromDate: "From Date",
    toDate: "To Date",
    clear: "Clear",
    excel: "Excel",
    print: "Print",
    period: "Period",
    generated: "Generated",
    noRecordsFound: "No records found.",
    totalBillableHours: "Total Billable Hours",
    employeeSignature: "Employee Signature",
    siteManagerApproval: "Site Manager Approval",
    hrSeal: "Human Resources Seal",
    correctShiftData: "Correct Shift Data",
    adminAuditOverride: "Admin Audit Override",
    publishCorrection: "Publish Correction",
    flagged: "Flagged",
    verified: "Verified",
    autoClosed: "Auto-Closed",
    pendingTermination: "Pending Termination",
    updateFailed: "Update failed.",
    dangerZoneTitle: "Danger Zone",
    dangerZoneSub: "Perform system-wide resets and destructive administrative tasks. These actions cannot be undone.",
    resetSystemTitle: "Reset All System Data & Start Fresh",
    resetSystemSub: "This will permanently purge all attendance records, holidays, announcements, assigned worksites, and registered employee profiles. Your administrator account is fully preserved.",
    resetDbBtn: "Reset Database",
    resettingText: "Resetting...",

    // Extra Translations
    syncingPayroll: "Syncing Payroll Data...",
    accessDenied: "Access Denied",
    backToReports: "Back to Reports",
    payrollOversight: "Payroll Oversight",
    reviewBillableHours: "Review billable hours and shift flags",
    manageHolidays: "Manage Holidays",
    syncing: "Syncing...",
    refresh: "Refresh",
    export: "Export",
    mudadWps: "Mudad WPS (.txt)",
    deleteOfficialHoliday: "Delete Official Holiday?",
    syncingNoticeBoard: "Syncing Notice Board...",
    bulkImport: "Bulk Import",
    bulkImportPreview: "Bulk Import Preview",
    importComplete: "Import Complete",
    addNewStaff: "Add New Staff",
    searchDirectory: "Search Directory",
    filterBySite: "Filter by Site",
    exportList: "Export List",
    noSitesAssigned: "No Sites Assigned",
    removeStaffTitle: "Remove Staff?",
    deleteProfileFor: "Delete profile for",
    activeSites: "Active Sites",
    addNewSite: "Add New Site",
    editWorksite: "Edit Worksite",
    newWorksite: "New Worksite",
    projectName: "Project Name",
    geofenceBoundary: "Geofence Boundary",
    captureMyGps: "Capture My GPS",
    radius: "Radius",
    assignStaff: "Assign Staff",
    findStaffPlaceholder: "Find staff...",
    noMatchingStaff: "No matching staff",
    applyChanges: "Apply Changes",
    flexibleSite: "Flexible Site",
    personnel: "Personnel",
    shiftSchedules: "Shift Schedules",
    defineWorkingHours: "Define working hours and assign staff to rotations",
    createShift: "Create Shift",
    editShift: "Edit Shift",
    newShiftConfig: "New Shift Configuration",
    shiftLabel: "Shift Label",
    startTime: "Start Time",
    endTime: "End Time",
    disableMidnightAutoClose: "Disable Midnight Auto-Close",
    allowSessionsMidnight: "Allow sessions to stay open across midnight (Ideal for Night Shifts)",
    workingDays: "Working Days",
    assignedPersonnel: "Assigned Personnel",
    applyScheduleConfig: "Apply Schedule Configuration",
    midnightClosureDisabled: "Midnight Closure Disabled",
    noActiveShiftSchedules: "No active shift schedules defined.",
    activeScanning: "Scanning Active Workforce...",
    activeAccessRestricted: "Access Restricted",
    activeDatabaseRestricted: "DATABASE_RESTRICTED: You don't have permission to view staff logs. Ensure your user profile is set to 'admin' and Firestore Rules are published.",
    activeFailedSync: "Failed to sync active operations.",
    activeRetrySync: "Retry Sync",
    activeOperations: "Active Operations",
    activeSubtext: "Real-time status of staff currently on shift",
    activeLive: "Live",
    activeUser: "User",
    activeUsers: "Users",
    activeColEmployee: "Employee",
    activeColClockedInAt: "Clocked In At",
    activeColSitePresence: "Site Presence",
    activeColShiftDuration: "Shift Duration",
    activeLeftAt: "Left at",
    activeOnSite: "On Site",
    activeAway: "Away",
    headlineMessageRequired: "Headline and Message are required.",
    confirmDeleteNotice: "Are you sure you want to delete this notice permanently?",
    noticeBoard: "Notice Board",
    noticeBoardSub: "Target specific worksites or individual personnel with updates",
    newNoticeBtn: "New Notice",
    editNoticeTitle: "Edit Notice",
    postNewNoticeTitle: "Post New Notice",
    priorityLabel: "Priority",
    subjectLabel: "Subject",
    subjectPlaceholder: "e.g. Mandatory Safety Briefing",
    messageDetailLabel: "Message Detail",
    messagePlaceholder: "Enter the notification text...",
    activeOnBoards: "Active on personnel boards",
    targetWorksitesMulti: "Target Worksites (Multi-Select)",
    targetPersonnelMulti: "Target Personnel (Multi-Select)",
    broadcastGlobal: "Broadcast Mode: Global (All Personnel)",
    broadcastTargeted: "Broadcast Mode: Targeted Restricted",
    publishNoticeBtn: "Publish Notice",
    noticeBoardClear: "The notice board is currently clear.",
    info: "Info",
    urgent: "Urgent",
    siteRestrict: "Site Restricted",
    personTarget: "Targeted Staff",
    department: "Department",
    operationsDept: "Operations",
    engineeringDept: "Engineering",
    managementDept: "Management",
    securityDept: "Security",
    systemRole: "System Role",
    standardUser: "Standard Employee / User",
    adminSupervisor: "Administrator / Supervisor",
    suspendAccess: "Suspend Profile / Access",
    preventUserClocking: "Prevent employee from checking in or logging shifts",
    searchStaffPlaceholder: "Search staff directory by name, email, ID or department...",
    allFieldsRequired: "All legal fields (Name, Email, Employee ID) are required.",
    confirmDeleteUser: "Are you sure you want to permanently remove this employee profile from the workspace?",
    scanningPersonnel: "Scanning organization personnel directory...",
    suspended: "Suspended",
    pleaseSelectEmployee: "Please select at least one employee.",
    noLogsFoundCriteria: "No logs found for the selected criteria.",
    exportFailed: "Export failed: ",
    consolidatedLogs: "Consolidated Logs",
    exportSubtext: "Export all employee logsheets into one report",
    generatingReport: "Generating Report...",
    exportExcelBtn: "Export Consolidated Excel",
    selectEmployees: "Select Employees",
    selectAllBtn: "Select All",
    flexibleSiteZone: "Flexible Site",
    safeZoneLabel: "Safe Zone",
    manageSiteSub: "Manage organization branches, worksites, GPS parameters and assign staff permissions",
    syncingWorksites: "Syncing Worksites...",
    provideValidName: "Please provide a valid name",
    confirmDeleteWorksite: "Are you sure you want to delete this worksite permanently?",
    deleteScheduleConfirm: "Delete this schedule?",
    shiftNameRequired: "Shift name is required",
    loadingSchedules: "Loading Schedules...",
    editProfileTitle: "Edit Profile",
    personnelInfoPolicies: "Personnel Information & Policies",
    identityAccess: "Identity & Access",
    fullLegalName: "Full Legal Name",
    corporateEmail: "Corporate Email",
    securityKeyPassword: "Security Key (Password)",
    minChars: "Min. 6 chars",
    employmentDetails: "Employment Details",
    staffId: "Staff ID",
    companyEntity: "Company Entity",
    payrollAttendancePolicy: "Payroll & Attendance Policy",
    grossSalarySR: "Gross Salary (SR)",
    targetMonthlyHours: "Target Monthly Hours",
    globalDefaultPlaceholder: "0 = Global Default",
    disableOvertime: "Disable Overtime",
    noPayExtraHours: "No pay for extra hours",
    disableDeductions: "Disable Deductions",
    noPenaltyShortHours: "No penalty for short hours",
    onLeaveStatus: "On Leave Status",
    markAwaySub: "Mark employee as currently away",
    leaveStartDate: "Leave Start Date",
    leaveEndDate: "Leave End Date",
    wpsMudadBankingInfo: "WPS / Mudad Banking Info",
    wpsSub: "Required for Saudi Wage Protection System export",
    iqamaNationalId: "Iqama / National ID",
    tenDigits: "10 digits",
    bankShortCode: "Bank Short Code",
    saCharsRequirement: "24 chars starting with SA",
    ibanWarning: "Must be 24 characters and start with SA",
    basicSalarySR: "Basic Salary (SR)",
    housingAllowanceSR: "Housing Allowance (SR)",
    otherAllowancesSR: "Other Allowances (SR)",
    wpsFilePreview: "WPS File Preview (this employee)",
    applyChangesBtn: "Apply Changes",
    createStaffProfileBtn: "Create Staff Profile",
    mandatoryFieldsError: "Mandatory Fields: Full Name, Email, and Staff ID are required.",
    securityKeyError: "Please set an initial security key (password) for the new user account.",
    securityKeyLengthError: "Security key must be at least 6 characters long.",
    joinExistingCompany: "Join Existing Company",
    registerNewCompany: "Register New Company",
    enterCompanyCode: "ENTER COMPANY CODE",
    chooseCompanyCode: "CHOOSE A COMPANY CODE",
    enterCompanyName: "ENTER COMPANY NAME",
    enterFullName: "ENTER YOUR FULL NAME",
    incorrectCredentialsError: "Incorrect Company ID, email, or security key. Please check your inputs.",
    emailAlreadyInUseError: "This email is already registered. Please sign in instead.",
    weakPasswordError: "Security key must be at least 6 characters.",
    firestorePermissionError: "CRITICAL: Firestore Permission Denied. Rules must be updated in Firebase Console.",
    unexpectedError: "An unexpected error occurred. Please try again.",
    pwaNotice: "For the best experience, use Safari on iOS or Chrome on Android and select \"Add to Home Screen\" from your browser menu.",
    permissionFixTitle: "Permission Fix Guide",
    databaseAccessSub: "Firestore Database Access",
    publishedRulesBtn: "I have published the rules",
    fixDatabaseRulesBtn: "Fix Database Rules Now",
    companyIdRequired: "Company ID is required.",
    fullNameRequired: "Full Name is required.",
    companyNameRequired: "Company Name is required to register a new company.",
    loginInfoSub: "• Enter your registered company code to log in.",
    registerNewCompanySub: "• Choose a unique code to register your company.",
    joinExistingCompanySub: "• Enter the company code provided by your manager to join.",
    payrollOversightSub: "Verify working hours, generate Saudi Wage Protection System (WPS) compliant salary files, and audit staff schedules.",
    manageHolidaysBtn: "Manage Holidays",
    printBtn: "Print",
    exportBtn: "Export",
    pdfReportOption: "PDF Report",
    excelOption: "Excel Spreadsheet",
    mudadOption: "Mudad / WPS Text",
    officialHolidays: "Official Holidays",
    nonWorkingDateMgmt: "Non-Working Date Management",
    holidayName: "Holiday Name",
    date: "Date",
    addToCalendar: "Add to Calendar",
    noHolidaysScheduled: "No holidays scheduled.",
    removeHolidayConfirm1: "This will remove",
    removeHolidayConfirm2: "from the global calendar.",
    company: "Company",
    projectSite: "Project / Site",
    staffMember: "Staff Member",
    allCompanies: "All Companies",
    allEmployees: "All Employees",
    unassignedSite: "Unassigned Site",
    noAttendanceDataFound: "No attendance data found.",
    onLeave: "On Leave",
    shiftsHeader: "Shifts",
    hoursHeader: "Hours",
    diffHeader: "Diff",
    flagsHeader: "Flags",
    grossHeader: "Gross",
    dayDedHeader: "Day Ded.",
    hourDedHeader: "Hour Ded.",
    totalDedHeader: "Total Ded.",
    otHeader: "OT",
    absDaysHeader: "Abs. Days",
    otherDedHeader: "Other Ded.",
    reimbHeader: "Reimb.",
    netHeader: "Net",
    noProjectAssigned: "No Project Assigned",
    unknownProject: "Unknown Project",
    projectSubtotal: "Project Subtotal",
    groupTotals: "Group Totals",
    grandTotals: "Grand Totals",
    multiCompanyTitle: "Multi-Company Switching",
    multiCompanySub: "Switch between multiple registered companies instantly, or link additional company accounts to manage.",
    linkedCompanies: "Your Linked Companies",
    activeContext: "Active Context",
    clickToSwitch: "Click to Switch",
    linkAnotherCompany: "Link Another Company ID",
    companyIdFieldLinkLabel: "Register/Link Company ID",
    linking: "Linking...",
    linkBtn: "Link Company",
    unlinkBtn: "Unlink",
    unlinkConfirm: "Are you sure you want to unlink this company? You will lose immediate access to switch to it."
  },
  ar: {
    // Nav
    navHome: "الرئيسية",
    navMyLogs: "سجلاتي",
    navReports: "التقارير",
    navLogExport: "تصدير السجلات",
    navActive: "النشطين الآن",
    navNotices: "الإشعارات",
    navStaff: "إدارة الموظفين",
    navSchedules: "الجدولة والورديات",
    navWorksite: "موقع العمل الجغرافي",
    navSettings: "الإعدادات",
    navSignOut: "تسجيل الخروج",
    navLogin: "تسجيل الدخول",
    navRegister: "إنشاء حساب جديد",

    // General
    save: "حفظ التغييرات",
    cancel: "إلغاء",
    admin: "مسؤول",
    employee: "موظف",
    loading: "جاري التحميل...",
    status: "الحالة",
    actions: "الإجراءات",
    edit: "تعديل",
    delete: "حذف",
    all: "الكل",
    warning: "تحذير",

    // Login / Register
    loginTitle: "الدخول إلى مساحة العمل",
    signUpTitle: "تسجيل مساحة عمل جديدة",
    tagline: "نظام ذكي وآمن لتسجيل حضور وانصراف الموظفين في الوقت الفعلي مع تفعيل النطاق الجغرافي التلقائي.",
    emailLabel: "البريد الإلكتروني للعمل",
    passwordLabel: "كلمة المرور",
    signInBtn: "تسجيل الدخول",
    noAccountText: "هل تحتاج إلى تسجيل شركة جديدة؟",
    signUpBtn: "تسجيل الشركة والمسؤول",
    fullNameLabel: "الاسم القانوني الكامل",
    companyIdLabel: "رمز تعريف الشركة (أحرف وأرقام)",
    companyNameLabel: "اسم الشركة التجاري",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    signingIn: "جاري تسجيل الدخول...",
    creatingWorkspace: "جاري إنشاء مساحة العمل...",

    // Dashboard
    goodMorning: "صباح الخير",
    welcomeBack: "مرحباً بعودتك",
    activeShift: "الوردية النشطة",
    noShiftToday: "لا توجد وردية مجدولة اليوم",
    geofenceStatus: "حالة النطاق الجغرافي",
    insideGeofence: "داخل نطاق موقع العمل",
    outsideGeofence: "خارج نطاق موقع العمل",
    locationChecking: "جاري التحقق من إحداثيات موقعك الحالي...",
    locationDisabled: "مطلوب الإذن بالوصول للموقع الجغرافي لتسجيل الحضور.",
    noActiveLogsToday: "لم تقم بتسجيل أي حضور اليوم.",
    clockedInSuccess: "تم تسجيل الحضور بنجاح!",
    clockedOutSuccess: "تم تسجيل الانصراف بنجاح!",
    selectProject: "اختر المشروع...",
    clockInBtn: "تسجيل الحضور (دخول)",
    clockOutBtn: "تسجيل الانصراف (خروج)",
    activeLogHeader: "سجل اليوم",
    hoursWorked: "الساعات المسجلة",
    ongoing: "مستمر",
    exemptionStatus: "حالة الاستثناء",
    nightShiftExemption: "استثناء وردية الليل نشط (لا إغلاق تلقائي)",
    noExemption: "القواعد القياسية (الإغلاق التلقائي 10 صباحاً)",
    todaysShift: "الساعات المجدولة:",
    selectProjectError: "يرجى تحديد المشروع قبل تسجيل الحضور.",

    // My Logs
    myLogsHeader: "سجل الحضور والغياب",
    myLogsSub: "عرض وتدقيق كافة سجلات الحضور والانصراف الخاصة بك",
    exportPdf: "تصدير تقرير PDF",
    dateCol: "التاريخ",
    projectCol: "المشروع",
    checkInCol: "وقت الحضور",
    checkOutCol: "وقت الانصراف",
    durationCol: "المدة",
    hrs: "ساعة",
    mins: "دقيقة",
    totalHours: "إجمالي الساعات",
    noLogsFound: "لا توجد سجلات حضور في هذه الفترة.",
    filterByMonth: "فلترة حسب الشهر",

    // Settings
    settingsHeader: "إعدادات الحساب",
    settingsSub: "إدارة بياناتك الشخصية، وتفضيلات مساحة العمل، وخصائص حسابك",
    personalInfoTitle: "المعلومات الشخصية",
    personalInfoSub: "التحقق من بيانات ملفك الشخصي وتحديثها",
    deptLabel: "القسم المخصص (للقراءة فقط)",
    employeeIdLabel: "الرقم الوظيفي للموظف",
    saveProfileBtn: "حفظ معلومات الملف الشخصي",
    savingProfile: "جاري حفظ الملف الشخصي...",
    companyProfileTitle: "ملف الشركة (للمسؤولين فقط)",
    companyProfileSub: "تعديل اسم الشركة التجاري ورمز التسجيل التعريفي",
    companyDisplayName: "اسم الشركة التجاري",
    companyRegId: "رمز تعريف الشركة",
    companyWarning: "تنبيه: تغيير رمز تعريف الشركة سيقوم بنقل بيانات جميع الموظفين والورديات والمشاريع والسجلات فورياً وبأمان إلى الرمز الجديد.",
    savingCompany: "جاري تحديث الشركة...",
    saveCompanyBtn: "حفظ إعدادات الشركة",
    passResetTitle: "تغيير كلمة المرور",
    passResetSub: "تحديث كلمة المرور لحسابك بشكل آمن",
    newPassLabel: "كلمة المرور الجديدة",
    confirmPassLabel: "تأكيد كلمة المرور الجديدة",
    savingPass: "جاري تحديث كلمة المرور...",
    savePassBtn: "تحديث كلمة المرور",
    activeCompany: "الشركة النشطة",
    companyIdFieldLabel: "معرف الشركة:",
    profilePhotoLabel: "صورة الملف الشخصي",
    selectPresetAvatar: "اختر صورة رمزية جاهزة",
    customPhotoUrl: "رابط الصورة المخصصة",
    saudiWpsMudadBankingDetails: "تفاصيل الحساب البنكي لنظام حماية الأجور (مدد)",
    iqamaLabel: "رقم الهوية الوطنية / الإقامة (10 أرقام)",
    bankCodeLabel: "رمز البنك",
    ibanLabel: "رقم الآيبان (24 خانة تبدأ بـ SA)",
    selectBank: "— اختر البنك —",

    // Admin Reports
    reportsTitle: "التقارير التنظيمية والمبيعات",
    reportsSub: "تحليل ذكي لبيانات الحضور، ومجموعات العمل، وساعات الرواتب والمستحقات",
    periodLabel: "فترة تصفية التاريخ المخصصة",
    allDepartments: "جميع الأقسام",
    allProjects: "جميع المشاريع",
    employeeNameCol: "اسم الموظف",
    workedDaysCol: "أيام العمل",
    totalHrsCol: "إجمالي الساعات",
    overtimeCol: "ساعات الإضافي",
    adjustmentsCol: "التعديلات والرواتب",
    deductionsLabel: "خصومات أخرى (ريال)",
    reimbursementsLabel: "التعويضات (ريال)",
    absentDaysLabel: "أيام الغياب",
    saveAdjustments: "حفظ تعديلات الرواتب",
    monthlyCyclesNote: "ملاحظة: تبدأ دورات الرواتب شهرياً من يوم 26 في الشهر السابق إلى يوم 25 في الشهر الحالي.",

    // Log Export
    exportTitle: "تصدير سجلات الحضور",
    exportSub: "تحميل تقارير شاملة لجميع سجلات النظام بصيغ إكسل أو PDF",
    exportCsvBtn: "تصدير إلى إكسل (CSV)",
    exportPdfBtn: "تصدير أرشيف (PDF)",
    exportPreviewTitle: "معاينة السجل",

    // Active Now
    activeTitle: "المتواجدون في العمل حالياً",
    activeSub: "عرض مباشر وتلقائي لجميع الموظفين الذين هم على رأس العمل الآن",
    noActiveStaff: "لا يوجد أي موظف مسجل حضور حالياً.",

    // Notices
    noticesTitle: "الإعلانات والتعميمات الإدارية",
    noticesSub: "نشر إعلانات وتوجيهها لمشاريع أو موظفين محددين",
    addNotice: "إنشاء إعلان جديد",
    noticeSubject: "الموضوع / العنوان",
    noticeContent: "نص الإعلان / الرسالة",
    targetProjects: "المشاريع المستهدفة (اتركه فارغاً للكل)",
    targetUsers: "الموظفين المستهدفين (اتركه فارغاً للكل)",
    publishBtn: "نشر الإعلان",
    activeBroadcasts: "الإعلانات النشطة الحالية",

    // Staff Management
    staffTitle: "دليل الموظفين والأدوار",
    staffSub: "تسجيل الموظفين وتعديل صلاحياتهم، ورواتبهم الأساسية، وتفاصيلهم",
    addStaffBtn: "تسجيل موظف جديد",
    editStaffTitle: "تعديل الملف الشخصي للموظف",
    roleLabel: "الصلاحية في مساحة العمل",
    salaryLabel: "الراتب الأساسي (ريال)",
    stdHoursLabel: "الساعات الشهرية القياسية",
    saveStaffBtn: "حفظ تفاصيل الموظف",

    // Schedules
    scheduleTitle: "الورديات ومواعيد العمل والغياب",
    scheduleSub: "تعيين ساعات الورديات واستثناءات وردية الليل للموظفين",
    addScheduleBtn: "إنشاء وردية عمل جديدة",
    daysLabel: "أيام العمل المطبقة",
    startEndLabel: "وقت البدء والانتهاء",
    disableAutoCloseLabel: "تفعيل وردية ليلية (تعطيل الإغلاق التلقائي 10 صباحاً)",

    // Worksite
    worksiteTitle: "النطاق الجغرافي وموقع العمل",
    worksiteSub: "تحديد إحداثيات GPS ونصف قطر المسافة المسموح بها لتسجيل الحضور للشركة",
    latitudeLabel: "خط العرض (Latitude)",
    longitudeLabel: "خط الطول (Longitude)",
    radiusLabel: "نصف القطر المسموح به (بالمتر)",
    saveWorksiteBtn: "حفظ إحداثيات موقع العمل",
    getCurrentLocationBtn: "جلب إحداثيات موقعي الحالي",

    // Dashboard Extras
    dbSub: "يتم تتبع الحضور عبر الحدود الجغرافية لموقع العمل",
    dbSelectMonitoringSite: "موقع المراقبة: اختر...",
    distanceLabel: "المسافة",
    dbNoWorksiteSelected: "لم يتم تحديد موقع عمل لتسجيل الدخول.",
    shiftInactive: "الوردية غير نشطة",
    dbChooseSite: "اختر موقع عمل للبدء",
    policyTitle: "سياسة الحضور",
    policyRule1: "تسجيل الحضور يتطلب التواجد الفعلي في الموقع.",
    policyRule2: "تسجيل الانصراف من أي مكان؛ ولكن يتم وسمه كخارج النطاق.",
    policyRule3: "الورديات غير المغلقة تنتهي تلقائياً الساعة 23:59 ما لم تكن مستثناة.",
    geofenceError: "قيود النطاق الجغرافي: يجب أن تكون في موقع العمل لتسجيل الحضور.",
    selectWorksiteError: "الرجاء تحديد موقع عمل أولاً.",
    shiftActionFailed: "فشل إجراء الوردية: ",
    shiftActive: "الوردية نشطة",
    hello: "مرحباً",
    insideSiteZone: "أنت داخل نطاق موقع العمل",
    outsideSiteZone: "تحذير: خارج نطاق موقع العمل",
    geofenceDisabled: "التحقق الجغرافي غير مفعل.",
    clockedInTime: "تم تسجيل الدخول في @",

    // History Extras
    fromDate: "من تاريخ",
    toDate: "إلى تاريخ",
    clear: "مسح",
    excel: "إكسل",
    print: "طباعة",
    period: "الفترة",
    generated: "تم إنشاؤه",
    noRecordsFound: "لم يتم العثور على سجلات.",
    totalBillableHours: "إجمالي الساعات الخاضعة للفوترة",
    employeeSignature: "توقيع الموظف",
    siteManagerApproval: "موافقة مدير الموقع",
    hrSeal: "ختم الموارد البشرية",
    correctShiftData: "تصحيح بيانات الوردية",
    adminAuditOverride: "تجاوز تدقيق المسؤول",
    publishCorrection: "نشر التصحيح",
    flagged: "موسوم",
    verified: "مؤكد",
    autoClosed: "مغلق تلقائياً",
    pendingTermination: "في انتظار الإنهاء",
    updateFailed: "فشل التحديث.",
    dangerZoneTitle: "منطقة الخطر",
    dangerZoneSub: "إجراء عمليات إعادة ضبط على مستوى النظام والمهام الإدارية المدمرة. لا يمكن التراجع عن هذه الإجراءات.",
    resetSystemTitle: "إعادة ضبط جميع بيانات النظام والبدء من جديد",
    resetSystemSub: "سيؤدي هذا إلى مسح جميع سجلات الحضور والعطلات والإعلانات ومواقع العمل المخصصة وملفات تعريف الموظفين المسجلين نهائيًا. يتم الاحتفاظ بحساب المسؤول الخاص بك بالكامل.",
    resetDbBtn: "إعادة ضبط قاعدة البيانات",
    resettingText: "جاري إعادة الضبط...",

    // Extra Translations
    syncingPayroll: "جاري مزامنة بيانات الرواتب...",
    accessDenied: "تم رفض الوصول",
    backToReports: "العودة إلى التقارير",
    payrollOversight: "الرقابة على الرواتب",
    reviewBillableHours: "مراجعة الساعات المعتمدة وعلامات الورديات",
    manageHolidays: "إدارة العطلات الرسمية",
    syncing: "جاري المزامنة...",
    refresh: "تحديث",
    export: "تصدير",
    mudadWps: "ملف نظام حماية الأجور مدد (.txt)",
    deleteOfficialHoliday: "حذف العطلة الرسمية؟",
    syncingNoticeBoard: "جاري مزامنة لوحة الإعلانات...",
    bulkImport: "استيراد جماعي",
    bulkImportPreview: "معاينة الاستيراد الجماعي",
    importComplete: "اكتمل الاستيراد",
    addNewStaff: "إضافة موظف جديد",
    searchDirectory: "البحث في الدليل",
    filterBySite: "تصفية حسب الموقع",
    exportList: "تصدير القائمة",
    noSitesAssigned: "لم يتم تعيين مواقع",
    removeStaffTitle: "إزالة الموظف؟",
    deleteProfileFor: "هل تريد حذف ملف تعريف الموظف",
    activeSites: "مواقع العمل النشطة",
    addNewSite: "إضافة موقع جديد",
    editWorksite: "تعديل موقع العمل",
    newWorksite: "موقع عمل جديد",
    projectName: "اسم المشروع",
    geofenceBoundary: "نطاق النطاق الجغرافي",
    captureMyGps: "التقاط إحداثيات GPS الخاصة بي",
    radius: "نصف القطر",
    assignStaff: "تعيين الموظفين",
    findStaffPlaceholder: "البحث عن موظف...",
    noMatchingStaff: "لا يوجد موظف مطابق",
    applyChanges: "تطبيق التغييرات",
    flexibleSite: "موقع عمل مرن",
    personnel: "الموظفين",
    shiftSchedules: "جداول الورديات",
    defineWorkingHours: "تحديد ساعات العمل وتعيين الموظفين للورديات",
    createShift: "إنشاء وردية",
    editShift: "تعديل الوردية",
    newShiftConfig: "إعداد وردية جديدة",
    shiftLabel: "مسمى الوردية",
    startTime: "وقت البدء",
    endTime: "وقت الانتهاء",
    disableMidnightAutoClose: "تعطيل الإغلاق التلقائي عند منتصف الليل",
    allowSessionsMidnight: "السماح للجلسات بالبقاء مفتوحة عبر منتصف الليل (مثالي لورديات الليل)",
    workingDays: "أيام العمل",
    assignedPersonnel: "الموظفون المعينون",
    applyScheduleConfig: "تطبيق إعدادات الجدول",
    midnightClosureDisabled: "تم تعطيل الإغلاق التلقائي عند منتصف الليل",
    noActiveShiftSchedules: "لم يتم تحديد جداول وردية نشطة.",
    activeScanning: "جاري البحث عن القوى العاملة النشطة...",
    activeAccessRestricted: "الوصول مقيد",
    activeDatabaseRestricted: "الوصول لقاعدة البيانات مقيد: ليس لديك صلاحية لعرض سجلات الموظفين. تأكد من أن حسابك مخصص كمسؤول وأن قواعد البيانات منشورة.",
    activeFailedSync: "فشل مزامنة العمليات النشطة.",
    activeRetrySync: "إعادة المحاولة",
    activeOperations: "العمليات النشطة",
    activeSubtext: "متابعة فورية للموظفين الموجودين في الوردية حالياً",
    activeLive: "مباشر",
    activeUser: "مستخدم",
    activeUsers: "مستخدمين",
    activeColEmployee: "الموظف",
    activeColClockedInAt: "وقت تسجيل الدخول",
    activeColSitePresence: "التواجد في الموقع",
    activeColShiftDuration: "مدة الوردية",
    activeLeftAt: "غادر في",
    activeOnSite: "في الموقع",
    activeAway: "خارج الموقع",
    headlineMessageRequired: "العنوان والرسالة مطلوبان.",
    confirmDeleteNotice: "هل أنت متأكد من رغبتك في حذف هذا الإعلان بشكل دائم؟",
    noticeBoard: "لوحة الإعلانات",
    noticeBoardSub: "استهداف مواقع عمل معينة أو موظفين محددين بالتحديثات الإدارية",
    newNoticeBtn: "إعلان جديد",
    editNoticeTitle: "تعديل الإعلان",
    postNewNoticeTitle: "نشر إعلان جديد",
    priorityLabel: "الأولوية",
    subjectLabel: "الموضوع",
    subjectPlaceholder: "مثال: إحاطة السلامة الإلزامية",
    messageDetailLabel: "تفاصيل الرسالة",
    messagePlaceholder: "أدخل نص الإعلان هنا...",
    activeOnBoards: "نشط على لوحة إعلانات الموظفين",
    targetWorksitesMulti: "مواقع العمل المستهدفة (تحديد متعدد)",
    targetPersonnelMulti: "الموظفون المستهدفون (تحديد متعدد)",
    broadcastGlobal: "طريقة البث: عام (جميع الموظفين)",
    broadcastTargeted: "طريقة البث: مخصص ومقيد",
    publishNoticeBtn: "نشر الإعلان",
    noticeBoardClear: "لوحة الإعلانات فارغة حالياً.",
    info: "معلومات",
    urgent: "عاجل",
    siteRestrict: "موقع محدد",
    personTarget: "موظف محدد",
    department: "القسم",
    operationsDept: "العمليات التشغيلية",
    engineeringDept: "الهندسة والمشاريع",
    managementDept: "الإدارة العامة",
    securityDept: "الحراسات الأمنية",
    systemRole: "صلاحية النظام",
    standardUser: "موظف عادي / مستخدم",
    adminSupervisor: "مدير / مشرف",
    suspendAccess: "تعليق الحساب / الدخول",
    preventUserClocking: "منع الموظف من تسجيل الحضور أو تسجيل النوبات",
    searchStaffPlaceholder: "البحث في دليل الموظفين بالاسم، الإيميل، الرقم الوظيفي أو القسم...",
    allFieldsRequired: "جميع الحقول الإلزامية (الاسم، البريد الإلكتروني، الرقم الوظيفي) مطلوبة.",
    confirmDeleteUser: "هل أنت متأكد من رغبتك في إزالة ملف هذا الموظف نهائياً من مساحة العمل؟",
    scanningPersonnel: "جاري فحص وتحديث دليل موظفي المنظمة...",
    suspended: "موقوف",
    pleaseSelectEmployee: "يرجى اختيار موظف واحد على الأقل.",
    noLogsFoundCriteria: "لم يتم العثور على سجلات تطابق المعايير المحددة.",
    exportFailed: "فشل التصدير: ",
    consolidatedLogs: "السجلات الموحدة",
    exportSubtext: "تصدير كافة سجلات الموظفين في تقرير واحد موحد",
    generatingReport: "جاري إنشاء التقرير...",
    exportExcelBtn: "تصدير السجل الموحد لإكسل",
    selectEmployees: "اختر الموظفين",
    selectAllBtn: "تحديد الكل",
    flexibleSiteZone: "موقع مرن",
    safeZoneLabel: "نطاق آمن",
    manageSiteSub: "إدارة فروع المؤسسة ومواقع العمل الجغرافية وتعيين صلاحيات الموظفين",
    syncingWorksites: "جاري مزامنة مواقع العمل...",
    provideValidName: "يرجى إدخال اسم صحيح",
    confirmDeleteWorksite: "هل أنت متأكد من رغبتك في حذف موقع العمل هذا بشكل دائم؟",
    deleteScheduleConfirm: "هل تريد حذف هذا الجدول الزمني؟",
    shiftNameRequired: "اسم الوردية مطلوب",
    loadingSchedules: "جاري تحميل جداول العمل...",
    editProfileTitle: "تعديل الملف الشخصي",
    personnelInfoPolicies: "معلومات وسياسات الموظفين",
    identityAccess: "الهوية وصلاحيات الوصول",
    fullLegalName: "الاسم القانوني الكامل",
    corporateEmail: "البريد الإلكتروني للشركة",
    securityKeyPassword: "مفتاح الأمان (كلمة المرور)",
    minChars: "6 أحرف كحد أدنى",
    employmentDetails: "تفاصيل العمل",
    staffId: "الرقم الوظيفي",
    companyEntity: "كيان الشركة",
    payrollAttendancePolicy: "سياسة الرواتب والحضور",
    grossSalarySR: "إجمالي الراتب (ريال سعودي)",
    targetMonthlyHours: "ساعات العمل الشهرية المستهدفة",
    globalDefaultPlaceholder: "0 = الافتراضي العام",
    disableOvertime: "تعطيل العمل الإضافي",
    noPayExtraHours: "لا يوجد دفع مقابل الساعات الإضافية",
    disableDeductions: "تعطيل الاستقطاعات",
    noPenaltyShortHours: "لا توجد عقوبة لتقصير الساعات",
    onLeaveStatus: "حالة الإجازة",
    markAwaySub: "تعليم الموظف كغائب/في إجازة حالياً",
    leaveStartDate: "تاريخ بدء الإجازة",
    leaveEndDate: "تاريخ انتهاء الإجازة",
    wpsMudadBankingInfo: "بيانات البنك الخاصة بـ (WPS) / مدد",
    wpsSub: "مطلوب لتصدير ملف نظام حماية الأجور السعودي",
    iqamaNationalId: "رقم الإقامة / الهوية الوطنية",
    tenDigits: "10 أرقام",
    bankShortCode: "رمز البنك المختصر",
    saCharsRequirement: "24 حرفاً تبدأ بـ SA",
    ibanWarning: "يجب أن يتكون الآيبان من 24 حرفاً ويبدأ بـ SA",
    basicSalarySR: "الراتب الأساسي (ريال)",
    housingAllowanceSR: "بدل السكن (ريال)",
    otherAllowancesSR: "البدلات الأخرى (ريال)",
    wpsFilePreview: "معاينة ملف نظام حماية الأجور (WPS) (لهذا الموظف)",
    applyChangesBtn: "تطبيق التغييرات",
    createStaffProfileBtn: "إنشاء ملف تعريف الموظف",
    mandatoryFieldsError: "الحقول الإلزامية: الاسم الكامل، البريد الإلكتروني، والرقم الوظيفي مطلوبة.",
    securityKeyError: "يرجى تعيين مفتاح أمان أولي (كلمة مرور) لحساب المستخدم الجديد.",
    securityKeyLengthError: "يجب أن يتكون مفتاح الأمان من 6 أحرف على الأقل.",
    joinExistingCompany: "الانضمام لشركة قائمة",
    registerNewCompany: "تسجيل شركة جديدة",
    enterCompanyCode: "أدخل رمز الشركة",
    chooseCompanyCode: "اختر رمز الشركة",
    enterCompanyName: "أدخل اسم الشركة",
    enterFullName: "أدخل اسمك الكامل",
    incorrectCredentialsError: "رمز الشركة، أو البريد الإلكتروني، أو مفتاح الأمان غير صحيح. يرجى التحقق من المدخلات.",
    emailAlreadyInUseError: "هذا البريد الإلكتروني مسجل بالفعل. يرجى تسجيل الدخول بدلاً من ذلك.",
    weakPasswordError: "يجب أن يتكون مفتاح الأمان من 6 أحرف على الأقل.",
    firestorePermissionError: "خطأ فادح: تم رفض الإذن بـ Firestore. يجب تحديث القواعد في Firebase Console.",
    unexpectedError: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
    pwaNotice: "للحصول على أفضل تجربة، استخدم Safari على iOS أو Chrome على Android واختر \"إضافة إلى الشاشة الرئيسية\" من قائمة المتصفح.",
    permissionFixTitle: "دليل إصلاح الصلاحيات",
    databaseAccessSub: "الوصول لقاعدة بيانات Firestore",
    publishedRulesBtn: "لقد قمت بنشر القواعد",
    fixDatabaseRulesBtn: "إصلاح قواعد قاعدة البيانات الآن",
    companyIdRequired: "رمز تعريف الشركة مطلوب.",
    fullNameRequired: "الاسم الكامل مطلوب.",
    companyNameRequired: "اسم الشركة مطلوب لتسجيل شركة جديدة.",
    loginInfoSub: "• أدخل رمز شركتك المسجل لتسجيل الدخول.",
    registerNewCompanySub: "• اختر رمزاً فريداً لتسجيل شركتك.",
    joinExistingCompanySub: "• أدخل رمز الشركة المقدم من مديرك للانضمام.",
    payrollOversightSub: "التحقق من ساعات العمل، وإنشاء ملفات الرواتب المتوافقة مع نظام حماية الأجور السعودي، وتدقيق جداول الموظفين.",
    manageHolidaysBtn: "إدارة الإجازات",
    printBtn: "طباعة",
    exportBtn: "تصدير",
    pdfReportOption: "تقرير PDF",
    excelOption: "جدول بيانات Excel",
    mudadOption: "ملف مدد / حماية الأجور",
    officialHolidays: "العطلات الرسمية",
    nonWorkingDateMgmt: "إدارة تواريخ العطلات",
    holidayName: "اسم العطلة",
    date: "التاريخ",
    addToCalendar: "إضافة للتقويم",
    noHolidaysScheduled: "لا توجد عطلات مجدولة.",
    removeHolidayConfirm1: "سيؤدي هذا إلى إزالة",
    removeHolidayConfirm2: "من التقويم العام.",
    company: "الشركة",
    projectSite: "المشروع / الموقع",
    staffMember: "الموظف",
    allCompanies: "جميع الشركات",
    allEmployees: "جميع الموظفين",
    unassignedSite: "موقع غير معين",
    noAttendanceDataFound: "لم يتم العثور على بيانات حضور.",
    onLeave: "في إجازة",
    shiftsHeader: "الورديات",
    hoursHeader: "الساعات",
    diffHeader: "الفرق",
    flagsHeader: "التنبيهات",
    grossHeader: "الأساسي",
    dayDedHeader: "خصم أيام",
    hourDedHeader: "خصم ساعات",
    totalDedHeader: "إجمالي الخصم",
    otHeader: "الإضافي",
    absDaysHeader: "أيام الغياب",
    otherDedHeader: "خصومات أخرى",
    reimbHeader: "التعويضات",
    netHeader: "الصافي",
    noProjectAssigned: "غير معين لمشروع",
    unknownProject: "مشروع غير معروف",
    projectSubtotal: "المجموع الفرعي للمشروع",
    groupTotals: "إجمالي المجموعة",
    grandTotals: "الإجمالي الكلي",
    multiCompanyTitle: "التبديل بين الشركات المتعددة",
    multiCompanySub: "التبديل بين عدة شركات مسجلة فوراً، أو ربط حسابات شركات إضافية لإدارتها.",
    linkedCompanies: "شركاتك المرتبطة",
    activeContext: "الشركة النشطة حالياً",
    clickToSwitch: "انقر للتحويل",
    linkAnotherCompany: "ربط معرف شركة آخر",
    companyIdFieldLinkLabel: "تسجيل/ربط معرف الشركة",
    linking: "جاري الربط...",
    linkBtn: "ربط الشركة",
    unlinkBtn: "إلغاء الارتباط",
    unlinkConfirm: "هل أنت متأكد من إلغاء ارتباط هذه الشركة؟ ستفقد القدرة الفورية على التبديل إليها."
  },
  de: {
    // Nav
    navHome: "Startseite",
    navMyLogs: "Meine Protokolle",
    navReports: "Berichte",
    navLogExport: "Protokollexport",
    navActive: "Aktiv Jetzt",
    navNotices: "Ankündigungen",
    navStaff: "Personalverwaltung",
    navSchedules: "Schichtpläne",
    navWorksite: "Arbeitsplatz-GPS",
    navSettings: "Einstellungen",
    navSignOut: "Abmelden",
    navLogin: "Anmelden",
    navRegister: "Registrieren",

    // General
    save: "Änderungen speichern",
    cancel: "Abbrechen",
    admin: "Admin",
    employee: "Mitarbeiter",
    loading: "Wird geladen...",
    status: "Status",
    actions: "Aktionen",
    edit: "Bearbeiten",
    delete: "Löschen",
    all: "Alle",
    warning: "Warnung",

    // Login
    loginTitle: "Workspace betreten",
    signUpTitle: "Workspace registrieren",
    tagline: "Sichere Zeiterfassung in Echtzeit mit automatischer Geofencing-Überwachung.",
    emailLabel: "Arbeits-E-Mail",
    passwordLabel: "Passwort",
    signInBtn: "Anmelden",
    noAccountText: "Neues Unternehmen registrieren?",
    signUpBtn: "Firma & Admin registrieren",
    fullNameLabel: "Vollständiger Name",
    companyIdLabel: "Unternehmens-ID (A-Z, 0-9)",
    companyNameLabel: "Name des Unternehmens",
    alreadyHaveAccount: "Bereits registriert?",
    signingIn: "Melde an...",
    creatingWorkspace: "Workspace wird erstellt...",

    // Dashboard
    goodMorning: "Guten Morgen",
    welcomeBack: "Willkommen zurück",
    activeShift: "Aktive Schicht",
    noShiftToday: "Heute keine Schicht geplant",
    geofenceStatus: "Geofence-Status",
    insideGeofence: "Innerhalb des Geofence",
    outsideGeofence: "Außerhalb des Geofence",
    locationChecking: "GPS-Koordinaten werden verifiziert...",
    locationDisabled: "Standortfreigabe ist für das Einchecken erforderlich.",
    noActiveLogsToday: "Sie haben heute noch keine Anwesenheit protokolliert.",
    clockedInSuccess: "Erfolgreich eingecheckt!",
    clockedOutSuccess: "Erfolgreich ausgecheckt!",
    selectProject: "Projekt auswählen...",
    clockInBtn: "Einchecken (Kommen)",
    clockOutBtn: "Auschecken (Gehen)",
    activeLogHeader: "Heutiges Protokoll",
    hoursWorked: "Arbeitsstunden",
    ongoing: "Laufend",
    exemptionStatus: "Ausnahmestatus",
    nightShiftExemption: "Nachtschicht-Ausnahme aktiv",
    noExemption: "Standardregeln (10 Uhr Auto-Abmeldung)",
    todaysShift: "Geplante Arbeitszeit:",
    selectProjectError: "Bitte wählen Sie ein Projekt aus, bevor Sie einchecken.",

    // My Logs
    myLogsHeader: "Anwesenheitsverlauf",
    myLogsSub: "Überprüfen Sie alle Ihre erfassten Kommen- und Gehen-Zeiten",
    exportPdf: "PDF-Bericht exportieren",
    dateCol: "Datum",
    projectCol: "Projekt",
    checkInCol: "Check In",
    checkOutCol: "Check Out",
    durationCol: "Dauer",
    hrs: "Std",
    mins: "Min",
    totalHours: "Gesamtstunden",
    noLogsFound: "Keine Anwesenheitsprotokolle für diesen Zeitraum gefunden.",
    filterByMonth: "Nach Monat filtern",

    // Settings
    settingsHeader: "Kontoeinstellungen",
    settingsSub: "Verwalten Sie Ihre persönlichen Anmeldedaten, Arbeitsbereicheinstellungen und Profilwerte",
    personalInfoTitle: "Persönliche Informationen",
    personalInfoSub: "Überprüfen Sie Ihre Profilparameter",
    deptLabel: "Zugewiesene Abteilung (Schreibgeschützt)",
    employeeIdLabel: "Mitarbeiter-ID",
    saveProfileBtn: "Profil speichern",
    savingProfile: "Profil wird gespeichert...",
    companyProfileTitle: "Unternehmensprofil (Nur Admin)",
    companyProfileSub: "Unternehmensdaten und Registrierungs-ID anpassen",
    companyDisplayName: "Name des Unternehmens",
    companyRegId: "Unternehmens-Registrierungs-ID",
    companyWarning: "Achtung: Durch Ändern der ID werden alle Mitarbeiter, Protokolle und Schichten dorthin migriert.",
    savingCompany: "Aktualisiere Unternehmen...",
    saveCompanyBtn: "Unternehmenseinstellungen speichern",
    passResetTitle: "Passwort zurücksetzen",
    passResetSub: "Ändern Sie Ihre Sicherheitsanmeldedaten",
    newPassLabel: "Neues Passwort",
    confirmPassLabel: "Passwort bestätigen",
    savingPass: "Passwort wird aktualisiert...",
    savePassBtn: "Passwort aktualisieren",

    // Admin Reports
    reportsTitle: "Berichte & Analysen",
    reportsSub: "Auswertung der Anwesenheitszeiten, Schichten und Lohnbuchhaltungszyklen",
    periodLabel: "Zeitraum filtern",
    allDepartments: "Alle Abteilungen",
    allProjects: "Alle Projekte",
    employeeNameCol: "Mitarbeiter",
    workedDaysCol: "Arbeitstage",
    totalHrsCol: "Gesamtstunden",
    overtimeCol: "Überstunden",
    adjustmentsCol: "Gehaltsanpassungen",
    deductionsLabel: "Abzüge (SAR)",
    reimbursementsLabel: "Erstattungen (SAR)",
    absentDaysLabel: "Fehltage",
    saveAdjustments: "Anpassungen speichern",
    monthlyCyclesNote: "Hinweis: Lohnabrechnungszyklen laufen vom 26. des Vormonats bis zum 25. des aktuellen Monats.",

    // Log Export
    exportTitle: "Protokollexport",
    exportSub: "Laden Sie umfassende Systemberichte als Excel oder PDF herunter",
    exportCsvBtn: "In Excel exportieren (CSV)",
    exportPdfBtn: "In PDF exportieren",
    exportPreviewTitle: "Vorschau",

    // Active Now
    activeTitle: "Derzeit eingecheckt",
    activeSub: "Echtzeit-Übersicht der Mitarbeiter im Dienst",
    noActiveStaff: "Derzeit ist kein Mitarbeiter eingecheckt.",

    // Notices
    noticesTitle: "Mitteilungen & Ankündigungen",
    noticesSub: "Posten Sie Ankündigungen für bestimmte Projekte oder Mitarbeiter",
    addNotice: "Neue Mitteilung erstellen",
    noticeSubject: "Betreff",
    noticeContent: "Inhalt",
    targetProjects: "Zielprojekte (Leer für alle)",
    targetUsers: "Zielmitarbeiter (Leer für alle)",
    publishBtn: "Veröffentlichen",
    activeBroadcasts: "Aktive Mitteilungen",

    // Staff
    staffTitle: "Mitarbeiterverzeichnis",
    staffSub: "Mitarbeiter registrieren, Rollen, Gehälter und Standardstunden verwalten",
    addStaffBtn: "Neuen Mitarbeiter registrieren",
    editStaffTitle: "Mitarbeiter bearbeiten",
    roleLabel: "Rolle im Workspace",
    salaryLabel: "Grundgehalt (SAR)",
    stdHoursLabel: "Standardstunden / Monat",
    saveStaffBtn: "Mitarbeiterdaten speichern",

    // Schedules
    scheduleTitle: "Schichtpläne & Ausnahmen",
    scheduleSub: "Schichtzeiten und Nachtschicht-Ausnahmen konfigurieren",
    addScheduleBtn: "Neuen Schichtplan erstellen",
    daysLabel: "Arbeitstage",
    startEndLabel: "Beginn & Ende",
    disableAutoCloseLabel: "Nachtschicht erlauben (Keine Auto-Abmeldung um 10 Uhr)",

    // Worksite
    worksiteTitle: "Geofence-Einstellungen",
    worksiteSub: "GPS-Koordinaten und zulässigen Erfassungsradius für den Arbeitsplatz festlegen",
    latitudeLabel: "Breitengrad",
    longitudeLabel: "Längengrad",
    radiusLabel: "Radius (Meter)",
    saveWorksiteBtn: "GPS-Koordinaten speichern",
    getCurrentLocationBtn: "Aktuellen Standort abrufen",

    // Dashboard Extras
    dbSub: "Anwesenheit erfasst via Geofencing-Standortgrenzen",
    dbSelectMonitoringSite: "Überwachungsstandort: Auswählen...",
    distanceLabel: "Entfernung",
    dbNoWorksiteSelected: "Kein Arbeitsplatz für das Einchecken ausgewählt.",
    shiftInactive: "Schicht inaktiv",
    dbChooseSite: "Wählen Sie einen Standort, um zu beginnen",
    policyTitle: "Anwesenheitsrichtlinie",
    policyRule1: "Einchecken erfordert physische Präsenz vor Ort.",
    policyRule2: "Auschecken überall möglich; markiert, wenn außerhalb der Zone.",
    policyRule3: "Unbeendete Schichten enden automatisch um 23:59 Uhr, sofern nicht befreit.",
    geofenceError: "Geofence-Einschränkung: Sie müssen sich am Arbeitsplatz befinden, um einzuchecken.",
    selectWorksiteError: "Bitte wählen Sie zuerst einen Arbeitsplatz aus.",
    shiftActionFailed: "Schichtaktion fehlgeschlagen: ",
    shiftActive: "Schicht aktiv",
    hello: "Hallo",
    insideSiteZone: "Sie befinden sich innerhalb der Standortzone",
    outsideSiteZone: "Warnung: Außerhalb der Standortgrenze",
    geofenceDisabled: "GPS-Verifizierung ist inaktiv oder deaktiviert.",
    clockedInTime: "Eingecheckt um @",

    // History Extras
    fromDate: "Von Datum",
    toDate: "Bis Datum",
    clear: "Löschen",
    excel: "Excel",
    print: "Drucken",
    period: "Zeitraum",
    generated: "Generiert",
    noRecordsFound: "Keine Datensätze gefunden.",
    totalBillableHours: "Abrechenbare Gesamtstunden",
    employeeSignature: "Unterschrift des Mitarbeiters",
    siteManagerApproval: "Genehmigung des Bauleiters",
    hrSeal: "Siegel der Personalabteilung",
    correctShiftData: "Schichtdaten korrigieren",
    adminAuditOverride: "Admin-Audit-Überschreibung",
    publishCorrection: "Korrektur veröffentlichen",
    flagged: "Markiert",
    verified: "Verifiziert",
    autoClosed: "Auto-geschlossen",
    pendingTermination: "Ausstehende Beendigung",
    updateFailed: "Update fehlgeschlagen."
  },
  fr: {
    // Nav
    navHome: "Accueil",
    navMyLogs: "Mes Logs",
    navReports: "Rapports",
    navLogExport: "Export Logs",
    navActive: "Actifs",
    navNotices: "Annonces",
    navStaff: "Gestion Personnel",
    navSchedules: "Plannings",
    navWorksite: "Géofence GPS",
    navSettings: "Paramètres",
    navSignOut: "Déconnexion",
    navLogin: "Connexion",
    navRegister: "S'inscrire",

    // General
    save: "Enregistrer",
    cancel: "Annuler",
    admin: "Admin",
    employee: "Employé",
    loading: "Chargement...",
    status: "Statut",
    actions: "Actions",
    edit: "Modifier",
    delete: "Supprimer",
    all: "Tous",
    warning: "Avertissement",

    // Login
    loginTitle: "Accéder à l'espace",
    signUpTitle: "Créer un espace",
    tagline: "Enregistrement de présence sécurisé en temps réel avec géolocalisation automatisée.",
    emailLabel: "E-mail professionnel",
    passwordLabel: "Mot de passe",
    signInBtn: "Se connecter",
    noAccountText: "Créer un espace pour votre entreprise ?",
    signUpBtn: "Créer Entreprise & Admin",
    fullNameLabel: "Nom complet",
    companyIdLabel: "ID d'entreprise (A-Z, 0-9)",
    companyNameLabel: "Nom d'affichage d'entreprise",
    alreadyHaveAccount: "Déjà inscrit ?",
    signingIn: "Connexion en cours...",
    creatingWorkspace: "Création de l'espace...",

    // Dashboard
    goodMorning: "Bonjour",
    welcomeBack: "Bon retour",
    activeShift: "Shift Actif",
    noShiftToday: "Aucun shift prévu aujourd'hui",
    geofenceStatus: "Statut Géofence",
    insideGeofence: "Dans la zone de travail",
    outsideGeofence: "Hors de la zone de travail",
    locationChecking: "Vérification des coordonnées GPS...",
    locationDisabled: "La localisation est obligatoire pour badger.",
    noActiveLogsToday: "Aucune présence enregistrée aujourd'hui.",
    clockedInSuccess: "Badgeage d'arrivée réussi !",
    clockedOutSuccess: "Badgeage de départ réussi !",
    selectProject: "Sélectionner un projet...",
    clockInBtn: "Badger Arrivée",
    clockOutBtn: "Badger Départ",
    activeLogHeader: "Badgeage du jour",
    hoursWorked: "Heures Travaillées",
    ongoing: "En cours",
    exemptionStatus: "Statut d'exemption",
    nightShiftExemption: "Exemption de shift de nuit active",
    noExemption: "Règles standard (Fermeture auto à 10h)",
    todaysShift: "Heures planifiées :",
    selectProjectError: "Veuillez sélectionner un projet avant de badger.",

    // My Logs
    myLogsHeader: "Historique des présences",
    myLogsSub: "Consultez et vérifiez tous vos logs d'arrivée et de départ",
    exportPdf: "Exporter en PDF",
    dateCol: "Date",
    projectCol: "Projet",
    checkInCol: "Badgeage d'arrivée",
    checkOutCol: "Badgeage de départ",
    durationCol: "Durée",
    hrs: "h",
    mins: "min",
    totalHours: "Total Heures",
    noLogsFound: "Aucun log de présence trouvé pour cette période.",
    filterByMonth: "Filtrer par mois",

    // Settings
    settingsHeader: "Paramètres du compte",
    settingsSub: "Gérez vos informations d'identification, préférences d'espace de travail et profil",
    personalInfoTitle: "Informations personnelles",
    personalInfoSub: "Vérifiez vos paramètres de profil",
    deptLabel: "Département assigné (Lecture seule)",
    employeeIdLabel: "Identifiant employé",
    saveProfileBtn: "Enregistrer le profil",
    savingProfile: "Enregistrement en cours...",
    companyProfileTitle: "Profil Entreprise (Admin seulement)",
    companyProfileSub: "Modifier le nom de l'entreprise et l'identifiant d'enregistrement",
    companyDisplayName: "Nom d'affichage d'entreprise",
    companyRegId: "Identifiant d'entreprise",
    companyWarning: "Attention: Modifier l'identifiant migrera automatiquement tous les employés et plannings vers le nouvel ID.",
    savingCompany: "Mise à jour de l'entreprise...",
    saveCompanyBtn: "Enregistrer les paramètres de l'entreprise",
    passResetTitle: "Changer le mot de passe",
    passResetSub: "Modifiez vos identifiants de sécurité",
    newPassLabel: "Nouveau mot de passe",
    confirmPassLabel: "Confirmer le mot de passe",
    savingPass: "Mise à jour du mot de passe...",
    savePassBtn: "Mettre à jour le mot de passe",

    // Admin Reports
    reportsTitle: "Rapports organisationnels",
    reportsSub: "Analyses des présences, des shifts et de la paie",
    periodLabel: "Période de filtrage",
    allDepartments: "Tous les départements",
    allProjects: "Tous les projets",
    employeeNameCol: "Nom employé",
    workedDaysCol: "Jours travaillés",
    totalHrsCol: "Heures totales",
    overtimeCol: "Heures supplémentaires",
    adjustmentsCol: "Ajustements de salaire",
    deductionsLabel: "Déductions (SAR)",
    reimbursementsLabel: "Remboursements (SAR)",
    absentDaysLabel: "Jours d'absence",
    saveAdjustments: "Enregistrer les ajustements",
    monthlyCyclesNote: "Note: Les cycles de paie mensuels vont du 26 du mois précédent au 25 du mois en cours.",

    // Log Export
    exportTitle: "Export des Logs",
    exportSub: "Téléchargez des rapports complets au format Excel ou PDF",
    exportCsvBtn: "Exporter en Excel (CSV)",
    exportPdfBtn: "Exporter en PDF",
    exportPreviewTitle: "Aperçu des logs",

    // Active Now
    activeTitle: "Présents actuellement",
    activeSub: "Vue en temps réel des employés en service",
    noActiveStaff: "Aucun employé n'est actuellement badgé.",

    // Notices
    noticesTitle: "Annonces d'entreprise",
    noticesSub: "Publiez des annonces ciblées par projet ou employé",
    addNotice: "Créer une annonce",
    noticeSubject: "Sujet",
    noticeContent: "Message / Contenu",
    targetProjects: "Projets ciblés (Vide pour tous)",
    targetUsers: "Personnel ciblé (Vide pour tous)",
    publishBtn: "Publier",
    activeBroadcasts: "Annonces actives",

    // Staff
    staffTitle: "Répertoire du personnel",
    staffSub: "Inscrire les employés, gérer les rôles, salaires et horaires mensuels standard",
    addStaffBtn: "Inscrire un nouvel employé",
    editStaffTitle: "Modifier la fiche de l'employé",
    roleLabel: "Rôle dans l'espace",
    salaryLabel: "Salaire de base (SAR)",
    stdHoursLabel: "Heures mensuelles standard",
    saveStaffBtn: "Enregistrer les détails de l'employé",

    // Schedules
    scheduleTitle: "Plannings & Exemptions",
    scheduleSub: "Configurer les horaires de shift et exemptions de nuit",
    addScheduleBtn: "Créer un planning",
    daysLabel: "Jours travaillés",
    startEndLabel: "Heures de début & fin",
    disableAutoCloseLabel: "Autoriser le shift de nuit (Pas de déconnexion auto à 10h)",

    // Worksite
    worksiteTitle: "Paramètres de Géofence",
    worksiteSub: "Définissez les coordonnées GPS et le rayon d'enregistrement toléré",
    latitudeLabel: "Latitude",
    longitudeLabel: "Longitude",
    radiusLabel: "Rayon de tolérance (mètres)",
    saveWorksiteBtn: "Enregistrer les coordonnées GPS",
    getCurrentLocationBtn: "Récupérer ma position actuelle",

    // Dashboard Extras
    dbSub: "Présence suivie via les limites de géolocalisation du site",
    dbSelectMonitoringSite: "Site de surveillance : Sélectionner...",
    distanceLabel: "Distance",
    dbNoWorksiteSelected: "Aucun site sélectionné pour le badgeage.",
    shiftInactive: "Shift inactif",
    dbChooseSite: "Choisissez un site pour commencer",
    policyTitle: "Politique de présence",
    policyRule1: "Le badgeage nécessite une présence physique sur le site.",
    policyRule2: "Badgeage de départ n'importe où ; signalé si hors zone.",
    policyRule3: "Les shifts non fermés se terminent automatiquement à 23:59 sauf exemption.",
    geofenceError: "Restriction géofence : Vous devez être sur le site pour badger.",
    selectWorksiteError: "Veuillez d'abord sélectionner un site.",
    shiftActionFailed: "Action de shift échouée : ",
    shiftActive: "Shift actif",
    hello: "Bonjour",
    insideSiteZone: "Vous êtes à l'intérieur de la zone du site",
    outsideSiteZone: "Attention : Hors des limites du site",
    geofenceDisabled: "Vérification GPS inactive ou désactivée.",
    clockedInTime: "Badgé à @",

    // History Extras
    fromDate: "Date de début",
    toDate: "Date de fin",
    clear: "Effacer",
    excel: "Excel",
    print: "Imprimer",
    period: "Période",
    generated: "Généré",
    noRecordsFound: "Aucun enregistrement trouvé.",
    totalBillableHours: "Heures facturables totales",
    employeeSignature: "Signature de l'employé",
    siteManagerApproval: "Approbation du responsable du site",
    hrSeal: "Sceau des ressources humaines",
    correctShiftData: "Corriger les données du shift",
    adminAuditOverride: "Contrôle d'audit administrateur",
    publishCorrection: "Publier la correction",
    flagged: "Signalé",
    verified: "Vérifié",
    autoClosed: "Fermé auto",
    pendingTermination: "En attente de fermeture",
    updateFailed: "Échec de la mise à jour."
  },
  es: {
    // Nav
    navHome: "Inicio",
    navMyLogs: "Mis Registros",
    navReports: "Informes",
    navLogExport: "Exportar Logs",
    navActive: "Activos Ahora",
    navNotices: "Avisos",
    navStaff: "Gestión de Personal",
    navSchedules: "Horarios",
    navWorksite: "Ubicación Geocerca",
    navSettings: "Ajustes",
    navSignOut: "Cerrar Sesión",
    navLogin: "Iniciar Sesión",
    navRegister: "Registrarse",

    // General
    save: "Guardar Cambios",
    cancel: "Cancelar",
    admin: "Admin",
    employee: "Empleado",
    loading: "Cargando...",
    status: "Estado",
    actions: "Acciones",
    edit: "Editar",
    delete: "Eliminar",
    all: "Todos",
    warning: "Advertencia",

    // Login
    loginTitle: "Acceso a su Área",
    signUpTitle: "Registrar Empresa",
    tagline: "Registro de asistencia seguro en tiempo real con geocercas automatizadas.",
    emailLabel: "Correo de Trabajo",
    passwordLabel: "Contraseña",
    signInBtn: "Iniciar Sesión",
    noAccountText: "¿Necesita registrar una empresa?",
    signUpBtn: "Registrar Empresa y Admin",
    fullNameLabel: "Nombre Legal Completo",
    companyIdLabel: "ID de Empresa (A-Z, 0-9)",
    companyNameLabel: "Nombre Comercial",
    alreadyHaveAccount: "¿Ya tiene cuenta?",
    signingIn: "Iniciando sesión...",
    creatingWorkspace: "Creando área de trabajo...",

    // Dashboard
    goodMorning: "Buenos Días",
    welcomeBack: "Bienvenido de nuevo",
    activeShift: "Turno Activo",
    noShiftToday: "Sin turno planificado hoy",
    geofenceStatus: "Estado de Geocerca",
    insideGeofence: "Dentro de la Zona de Trabajo",
    outsideGeofence: "Fuera de la Zona de Trabajo",
    locationChecking: "Verificando coordenadas GPS...",
    locationDisabled: "El acceso a la ubicación es obligatorio para fichar.",
    noActiveLogsToday: "Aún no ha registrado asistencia hoy.",
    clockedInSuccess: "¡Asistencia registrada correctamente!",
    clockedOutSuccess: "¡Salida registrada correctamente!",
    selectProject: "Seleccionar Proyecto...",
    clockInBtn: "Fichar Entrada",
    clockOutBtn: "Fichar Salida",
    activeLogHeader: "Registro de Hoy",
    hoursWorked: "Horas Trabajadas",
    ongoing: "En Curso",
    exemptionStatus: "Estado de Exención",
    nightShiftExemption: "Exención de Turno Nocturno Activa",
    noExemption: "Reglas Estándar (Cierre automático 10 AM)",
    todaysShift: "Horas planificadas:",
    selectProjectError: "Por favor seleccione un proyecto antes de registrar entrada.",

    // My Logs
    myLogsHeader: "Historial de Asistencia",
    myLogsSub: "Consulte y verifique todos sus registros de entrada y salida",
    exportPdf: "Exportar Reporte PDF",
    dateCol: "Fecha",
    projectCol: "Proyecto",
    checkInCol: "Entrada",
    checkOutCol: "Salida",
    durationCol: "Duración",
    hrs: "hrs",
    mins: "mins",
    totalHours: "Total Horas",
    noLogsFound: "No se encontraron registros en este periodo.",
    filterByMonth: "Filtrar por Mes",

    // Settings
    settingsHeader: "Ajustes del Cuenta",
    settingsSub: "Gestione sus credenciales, preferencias de espacio de trabajo y perfil",
    personalInfoTitle: "Información Personal",
    personalInfoSub: "Verifique sus parámetros de perfil",
    deptLabel: "Departamento Asignado (Solo lectura)",
    employeeIdLabel: "ID de Empleado",
    saveProfileBtn: "Guardar Información",
    savingProfile: "Guardando perfil...",
    companyProfileTitle: "Perfil de Empresa (Solo Admin)",
    companyProfileSub: "Modificar nombre de empresa y ID de registro",
    companyDisplayName: "Nombre de Empresa",
    companyRegId: "ID de Registro de Empresa",
    companyWarning: "Advertencia: Cambiar el ID de la empresa migrará de forma segura todo el personal, horarios y logs.",
    savingCompany: "Actualizando Empresa...",
    saveCompanyBtn: "Guardar Ajustes de Empresa",
    passResetTitle: "Restablecer Contraseña",
    passResetSub: "Cambie sus credenciales de seguridad",
    newPassLabel: "Nueva Contraseña",
    confirmPassLabel: "Confirmar Contraseña",
    savingPass: "Actualizando contraseña...",
    savePassBtn: "Actualizar Contraseña",

    // Admin Reports
    reportsTitle: "Informes Organizacionales",
    reportsSub: "Métricas de asistencia, turnos y nóminas",
    periodLabel: "Periodo de fecha de filtro",
    allDepartments: "Todos los departamentos",
    allProjects: "Todos los proyectos",
    employeeNameCol: "Empleado",
    workedDaysCol: "Días Trabajados",
    totalHrsCol: "Horas Totales",
    overtimeCol: "Horas Extra",
    adjustmentsCol: "Ajustes de Nómina",
    deductionsLabel: "Otras Deducciones (SAR)",
    reimbursementsLabel: "Reembolsos (SAR)",
    absentDaysLabel: "Días de Ausencia",
    saveAdjustments: "Guardar Ajustes",
    monthlyCyclesNote: "Nota: Los ciclos de nómina mensuales van del 26 del mes anterior al 25 del mes actual.",

    // Log Export
    exportTitle: "Exportar Logs",
    exportSub: "Descargue reportes detallados en formato Excel o PDF",
    exportCsvBtn: "Exportar a Excel (CSV)",
    exportPdfBtn: "Exportar a PDF",
    exportPreviewTitle: "Vista Previa",

    // Active Now
    activeTitle: "Presentes Ahora",
    activeSub: "Vista en tiempo real del personal en servicio",
    noActiveStaff: "Ningún empleado está fichado actualmente.",

    // Notices
    noticesTitle: "Avisos de la Empresa",
    noticesSub: "Publique anuncios dirigidos a proyectos o empleados específicos",
    addNotice: "Crear Nuevo Anuncio",
    noticeSubject: "Asunto",
    noticeContent: "Mensaje / Contenido",
    targetProjects: "Proyectos Objetivo (Vacío para todos)",
    targetUsers: "Personal Objetivo (Vacío para todos)",
    publishBtn: "Publicar Anuncio",
    activeBroadcasts: "Anuncios Activos",

    // Staff
    staffTitle: "Directorio de Personal",
    staffSub: "Registrar empleados, gestionar roles, salarios y horas estándar",
    addStaffBtn: "Registrar Nuevo Empleado",
    editStaffTitle: "Editar Empleado",
    roleLabel: "Rol en Workspace",
    salaryLabel: "Salario Base (SAR)",
    stdHoursLabel: "Horas Estándar Mensuales",
    saveStaffBtn: "Guardar Datos de Empleado",

    // Schedules
    scheduleTitle: "Horarios & Exenciones",
    scheduleSub: "Configurar turnos de trabajo y exenciones nocturnas",
    addScheduleBtn: "Crear Nuevo Horario",
    daysLabel: "Días de Trabajo",
    startEndLabel: "Entrada & Salida",
    disableAutoCloseLabel: "Habilitar Turno Nocturno (Desactiva cierre automático 10 AM)",

    // Worksite
    worksiteTitle: "Ajustes de Geocerca",
    worksiteSub: "Configure las coordenadas GPS y el radio de tolerancia de entrada",
    latitudeLabel: "Latitud",
    longitudeLabel: "Longitud",
    radiusLabel: "Radio de Tolerancia (Metros)",
    saveWorksiteBtn: "Guardar Coordenadas GPS",
    getCurrentLocationBtn: "Obtener Ubicación Actual",

    // Dashboard Extras
    dbSub: "Asistencia rastreada a través de límites geocercados",
    dbSelectMonitoringSite: "Sitio de monitoreo: Seleccionar...",
    distanceLabel: "Distancia",
    dbNoWorksiteSelected: "No se seleccionó ningún lugar de trabajo para registrar entrada.",
    shiftInactive: "Turno inactivo",
    dbChooseSite: "Elija un sitio para comenzar",
    policyTitle: "Política de Asistencia",
    policyRule1: "Fichar entrada requiere presencia física en el sitio.",
    policyRule2: "Fichar salida en cualquier lugar; marcado si está fuera de zona.",
    policyRule3: "Los turnos no cerrados terminan automáticamente a las 23:59 a menos que estén exentos.",
    geofenceError: "Restricción de geocerca: Debe estar en el lugar de trabajo para fichar entrada.",
    selectWorksiteError: "Por favor seleccione un lugar de trabajo primero.",
    shiftActionFailed: "Acción de turno fallida: ",
    shiftActive: "Turno activo",
    hello: "Hola",
    insideSiteZone: "Está dentro de la zona del sitio",
    outsideSiteZone: "Advertencia: Fuera del límite del sitio",
    geofenceDisabled: "La verificación de GPS está inactiva o deshabilitada.",
    clockedInTime: "Entrada registrada @ ",

    // History Extras
    fromDate: "Desde fecha",
    toDate: "Hasta fecha",
    clear: "Limpiar",
    excel: "Excel",
    print: "Imprimir",
    period: "Periodo",
    generated: "Generado",
    noRecordsFound: "No se encontraron registros.",
    totalBillableHours: "Total horas facturables",
    employeeSignature: "Firma del empleado",
    siteManagerApproval: "Aprobación del director de obra",
    hrSeal: "Sello de recursos humanos",
    correctShiftData: "Corregir datos de turno",
    adminAuditOverride: "Anulación de auditoría de administrador",
    publishCorrection: "Publicar corrección",
    flagged: "Marcado",
    verified: "Verificado",
    autoClosed: "Cerrado auto",
    pendingTermination: "Terminación pendiente",
    updateFailed: "Actualización fallida."
  },
  tr: {
    // Nav
    navHome: "Ana Sayfa",
    navMyLogs: "Kayıtlarım",
    navReports: "Raporlar",
    navLogExport: "Kayıt Dışa Aktar",
    navActive: "Aktif Personel",
    navNotices: "Duyurular",
    navStaff: "Personel Yönetimi",
    navSchedules: "Vardiyalar",
    navWorksite: "Konum Sınırları",
    navSettings: "Ayarlar",
    navSignOut: "Çıkış Yap",
    navLogin: "Giriş Yap",
    navRegister: "Kayıt Ol",

    // General
    save: "Değişiklikleri Kaydet",
    cancel: "İptal",
    admin: "Yönetici",
    employee: "Personel",
    loading: "Yükleniyor...",
    status: "Durum",
    actions: "İşlemler",
    edit: "Düzenle",
    delete: "Sil",
    all: "Tümü",
    warning: "Uyarı",

    // Login
    loginTitle: "Çalışma Alanına Giriş",
    signUpTitle: "Yeni Şirket Kaydı",
    tagline: "Otomatik GPS geofence ile güvenli, gerçek zamanlı iş yeri personel takibi.",
    emailLabel: "İş E-postası",
    passwordLabel: "Şifre",
    signInBtn: "Giriş Yap",
    noAccountText: "Yeni bir şirket çalışma alanı mı lazım?",
    signUpBtn: "Şirket & Yönetici Kaydet",
    fullNameLabel: "Tam Adı Soyadı",
    companyIdLabel: "Şirket Kodu (A-Z, 0-9)",
    companyNameLabel: "Şirket Adı",
    alreadyHaveAccount: "Zaten üye misiniz?",
    signingIn: "Giriş yapılıyor...",
    creatingWorkspace: "Çalışma alanı kuruluyor...",

    // Dashboard
    goodMorning: "Günaydın",
    welcomeBack: "Tekrar Hoş Geldiniz",
    activeShift: "Aktif Vardiya",
    noShiftToday: "Bugün planlanmış vardiyanız yok",
    geofenceStatus: "Konum Sınırı Durumu",
    insideGeofence: "Çalışma Sahası İçinde",
    outsideGeofence: "Çalışma Sahası Dışında",
    locationChecking: "GPS konumunuz doğrulanıyor...",
    locationDisabled: "Giriş yapmak için konum izni gereklidir.",
    noActiveLogsToday: "Bugün henüz giriş-çıkış kaydınız bulunmuyor.",
    clockedInSuccess: "Giriş kaydı başarıyla yapıldı!",
    clockedOutSuccess: "Çıkış kaydı başarıyla yapıldı!",
    selectProject: "Proje Seçin...",
    clockInBtn: "Giriş Yap (Geldi)",
    clockOutBtn: "Çıkış Yap (Gitti)",
    activeLogHeader: "Bugünkü Kayıt",
    hoursWorked: "Çalışma Süresi",
    ongoing: "Devam Ediyor",
    exemptionStatus: "Muafiyet Durumu",
    nightShiftExemption: "Gece Vardiyası Muafiyeti Aktif",
    noExemption: "Standart Kurallar (Saat 10:00'da Otomatik Kapatma)",
    todaysShift: "Planlanmış Saatler:",
    selectProjectError: "Lütfen giriş yapmadan önce bir proje seçin.",

    // My Logs
    myLogsHeader: "Giriş Çıkış Geçmişi",
    myLogsSub: "Tüm kayıtlı giriş ve çıkış bilgilerinizi listeleyin ve kontrol edin",
    exportPdf: "PDF Raporu İndir",
    dateCol: "Tarih",
    projectCol: "Proje",
    checkInCol: "Giriş Saati",
    checkOutCol: "Çıkış Saati",
    durationCol: "Süre",
    hrs: "sa",
    mins: "dk",
    totalHours: "Toplam Çalışma",
    noLogsFound: "Bu dönemde kayıt bulunamadı.",
    filterByMonth: "Aya Göre Filtrele",

    // Settings
    settingsHeader: "Hesap Ayarları",
    settingsSub: "Kişisel kimlik bilgilerinizi, çalışma alanı tercihlerinizi ve profil ayarlarınızı yönetin",
    personalInfoTitle: "Kişisel Bilgiler",
    personalInfoSub: "Profil ayarlarınızı güncelleyin",
    deptLabel: "Tanımlı Departman (Salt okunur)",
    employeeIdLabel: "Personel / Sicil No",
    saveProfileBtn: "Profili Kaydet",
    savingProfile: "Profil kaydediliyor...",
    companyProfileTitle: "Şirket Profili (Sadece Yönetici)",
    companyProfileSub: "Şirket adını ve kayıt kodunu düzenleyin",
    companyDisplayName: "Şirket Adı",
    companyRegId: "Şirket Kayıt Kodu",
    companyWarning: "Uyarı: Şirket kodunu değiştirmek, tüm çalışanları, vardiyaları ve kayıtları güvenli şekilde yeni koda taşıyacaktır.",
    savingCompany: "Şirket Güncelleniyor...",
    saveCompanyBtn: "Şirket Ayarlarını Kaydet",
    passResetTitle: "Şifre Sıfırlama",
    passResetSub: "Güvenlik şifrenizi güncelleyin",
    newPassLabel: "Yeni Şifre",
    confirmPassLabel: "Şifre Onay",
    savingPass: "Şifre güncelleniyor...",
    savePassBtn: "Şifreyi Güncelle",

    // Admin Reports
    reportsTitle: "Kurumsal Raporlar",
    reportsSub: "Çalışma saatleri analizi, vardiyalar ve maaş hakediş döngüleri",
    periodLabel: "Tarih Filtresi Aralığı",
    allDepartments: "Tüm Departmanlar",
    allProjects: "Tüm Projeler",
    employeeNameCol: "Personel Adı",
    workedDaysCol: "Çalıştığı Gün",
    totalHrsCol: "Toplam Saat",
    overtimeCol: "Fazla Mesai",
    adjustmentsCol: "Maaş Düzenlemeleri",
    deductionsLabel: "Diğer Kesintiler (SAR)",
    reimbursementsLabel: "Geri Ödemeler (SAR)",
    absentDaysLabel: "Devamsız Gün Sayısı",
    saveAdjustments: "Düzenlemeleri Kaydet",
    monthlyCyclesNote: "Not: Maaş hesaplama döngüleri her ayın 26'sından bir sonraki ayın 25'ine kadar olan dönemi kapsar.",

    // Log Export
    exportTitle: "Kayıtları Dışa Aktar",
    exportSub: "Tüm sistem kayıtlarını Excel veya PDF olarak indirin",
    exportCsvBtn: "Excel Dosyası (CSV)",
    exportPdfBtn: "PDF Arşivi",
    exportPreviewTitle: "Kayıt Önizleme",

    // Active Now
    activeTitle: "Şu An Çalışanlar",
    activeSub: "Görevde olan personellerin gerçek zamanlı listesi",
    noActiveStaff: "Şu an aktif olarak çalışmakta olan personel bulunmuyor.",

    // Notices
    noticesTitle: "Şirket Duyuruları",
    noticesSub: "Belirli projelere veya personele yönelik kurumsal duyurular yayınlayın",
    addNotice: "Yeni Duyuru Yayınla",
    noticeSubject: "Konu / Başlık",
    noticeContent: "İçerik",
    targetProjects: "Hedef Projeler (Herkes için boş bırakın)",
    targetUsers: "Hedef Personel (Herkes için boş bırakın)",
    publishBtn: "Duyuruyu Yayınla",
    activeBroadcasts: "Yayındaki Duyurular",

    // Staff
    staffTitle: "Personel Rehberi",
    staffSub: "Çalışan kaydı oluşturun, rolleri, maaşları ve çalışma sürelerini yönetin",
    addStaffBtn: "Yeni Personel Kaydet",
    editStaffTitle: "Personel Bilgilerini Düzenle",
    roleLabel: "Çalışma Alanı Rolü",
    salaryLabel: "Taban Maaş (SAR)",
    stdHoursLabel: "Standart Aylık Saat",
    saveStaffBtn: "Personel Bilgilerini Kaydet",

    // Schedules
    scheduleTitle: "Vardiya & Çalışma Planları",
    scheduleSub: "Personel çalışma saatlerini ve gece vardiyası muafiyetlerini ayarlayın",
    addScheduleBtn: "Yeni Vardiya Planı Oluştur",
    daysLabel: "Çalışma Günleri",
    startEndLabel: "Giriş & Çıkış Saatleri",
    disableAutoCloseLabel: "Gece Vardiyasını Etkinleştir (Saat 10:00'da Otomatik Kapatma Pasif)",

    // Worksite
    worksiteTitle: "Konum Sınırlandırması",
    worksiteSub: "Giriş yapılabilecek GPS konumunu ve kabul edilebilir mesafe yarıçapını belirleyin",
    latitudeLabel: "Enlem (Latitude)",
    longitudeLabel: "Boylam (Longitude)",
    radiusLabel: "İzin Verilen Yarıçap (Metre)",
    saveWorksiteBtn: "GPS Bilgilerini Kaydet",
    getCurrentLocationBtn: "Geçerli Konumumu Al",

    // Dashboard Extras
    dbSub: "GPS geofence konum sınırları ile takip edilen katılım",
    dbSelectMonitoringSite: "İzleme Sahası: Seçin...",
    distanceLabel: "Mesafe",
    dbNoWorksiteSelected: "Giriş için herhangi bir çalışma alanı seçilmedi.",
    shiftInactive: "Vardiya Pasif",
    dbChooseSite: "Başlamak için bir saha seçin",
    policyTitle: "Katılım Politikası",
    policyRule1: "Giriş yapmak sahada fiziksel varlık gerektirir.",
    policyRule2: "Herhangi bir yerde çıkış yapılabilir; ancak saha dışındaysa işaretlenir.",
    policyRule3: "Kapatılmayan vardiyalar, muafiyet yoksa 23:59'da otomatik olarak sonlandırılır.",
    geofenceError: "GPS Sınır Kısıtlaması: Giriş yapmak için çalışma alanında bulunmalısınız.",
    selectWorksiteError: "Lütfen önce bir çalışma alanı seçin.",
    shiftActionFailed: "Vardiya işlemi başarısız: ",
    shiftActive: "Vardiya Aktif",
    hello: "Merhaba",
    insideSiteZone: "Çalışma sahası sınırları içerisindesiniz",
    outsideSiteZone: "Uyarı: Çalışma sahası sınırları dışındasınız",
    geofenceDisabled: "GPS doğrulaması aktif değil veya devre dışı bırakıldı.",
    clockedInTime: "Giriş saati @",

    // History Extras
    fromDate: "Başlangıç Tarihi",
    toDate: "Bitiş Tarihi",
    clear: "Temizle",
    excel: "Excel",
    print: "Yazdır",
    period: "Dönem",
    generated: "Oluşturulma",
    noRecordsFound: "Kayıt bulunamadı.",
    totalBillableHours: "Toplam Faturalanabilir Saat",
    employeeSignature: "Personel İmzası",
    siteManagerApproval: "Şantiye Şefi Onayı",
    hrSeal: "İnsan Kaynakları Mührü",
    correctShiftData: "Vardiya Verilerini Düzelt",
    adminAuditOverride: "Yönetici Denetim Geçersiz Kılması",
    publishCorrection: "Düzeltmeyi Yayınla",
    flagged: "İşaretli",
    verified: "Doğrulandı",
    autoClosed: "Otomatik Kapatıldı",
    pendingTermination: "Sonlandırma Bekliyor",
    updateFailed: "Güncelleme başarısız."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageType>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved as LanguageType) || 'en';
  });

  const setLanguage = (lang: LanguageType) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  const isRtl = language === 'ar';

  useEffect(() => {
    // Dynamically update document layout properties
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRtl]);

  const t = (key: string): string => {
    const dict = translations[language];
    if (dict && dict[key]) {
      return dict[key];
    }
    // Fallback to English
    const fallbackDict = translations['en'];
    if (fallbackDict && fallbackDict[key]) {
      return fallbackDict[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
